### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by gengjiawen** [hongyangAndroid/Android-StickyNavLayout#1]
com.zhy.view.StickyNavLayout.getCurrentScrollView()方法中 
mInnerScrollView = (ScrollView) (item.getView().findViewById(R.id.id_stickynavlayout_innerscrollview));
可能会出现空指针,启动后做些操作放在后台运行再打开就有可能出现这个

**Comment by zeng1990java** [comment]
Fragment item = fsAdapter.getItem(currentItem);
这句代码改成
Fragment item = (Fragment) fadapter.instantiateItem(mViewPager, currentItem);
就好了
