### ISSUE TITLE
when listview is empty

### ISSUE THREAD

**Issue by yankai-victor** [hongyangAndroid/Android-StickyNavLayout#2]
1.When listview in viewpager is empty and the topview is hidden, I scroll down the listview, the topview doesn't show.
solution:
Change the code in 124
if (!isTopHidden || (c != null && c.getTop() == 0 && isTopHidden && dy > 0) || lv.getCount() == 0)

2.If view in topview is changed its visibility, the mTopViewHeight doesn't change the value. So I can't scoll up to hide the topview.
solution:add mTopViewHeight = mTop.getMeasuredHeight(); in onMeasure()

1.当viewpager中的listview没有数据，并且topview已经上滑隐藏后，再下拉listview时，topview并没有能向预期中的慢慢出现。
解决的办法：修改124的代码为
if (!isTopHidden || (c != null && c.getTop() == 0 && isTopHidden && dy > 0) || lv.getCount() == 0) 
添加了 lv.getCount() == 0的情况

2.当topview中的某个view修改visibility控制其显示隐藏时，mTopViewHeight的值不会改变，所以在滑动的过程中可能不能将topview完全隐藏。类似的只要某个view动态改变大小后，都会有这种情况。
解决办法：
在 onMeasure()方法中添加mTopViewHeight = mTop.getMeasuredHeight();
即当view改变时，重新计算mTopViewHeight的高度。

**Comment by hongyangAndroid** [comment]
thanks for your contribution .
